import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tradeiq_app/core/theme/torchlight/entry_skin.dart';
import 'package:tradeiq_app/core/theme/torchlight/tiq_contrast.dart';
import 'package:tradeiq_app/core/theme/torchlight/tiq_skin.dart';
import 'package:tradeiq_app/core/widgets/torchlight/chrome/chrome.dart';
import 'package:tradeiq_app/core/widgets/torchlight/display_headline.dart';
import 'package:tradeiq_app/core/widgets/torchlight/plate/plate.dart';
import 'package:tradeiq_app/features/auth/presentation/entry_brand.dart';
import 'package:tradeiq_app/features/auth/presentation/entry_plate.dart';
import 'package:tradeiq_app/features/auth/presentation/login_screen.dart';

import '../agent_harness.dart' show loadAgentFonts;
import 'entry_harness.dart';

/// THE PLATE ON THE DOOR — the pins behind `entry_plate.dart`.
///
/// `entry_look_test.dart` is the picture and `entry_amber_census_test.dart`
/// counts the light. This file answers the four questions neither can:
///
/// 1. **Is the picture the one we are allowed to ship, and is it still that
///    picture?** Three separate claims were made about `ALL.jpg` when it was
///    chosen and all three are checked here against the files that carry
///    them, not against anybody's memory.
/// 2. **Does the fold arithmetic actually produce the three shapes the design
///    claims?** A 250dp photographic plate on a 390×844 phone and on a
///    1280×1800 browser, and the collapsed band on a 360×640 handset.
/// 3. **Is the strip light out, in both skins?** The amber census counts
///    objects; this asserts the specific thing that would make that count
///    wrong, which is the plate's own light being lit.
/// 4. **Does the ink on the picture clear 4.5:1?** Measured over the real
///    asset, in both skins, at all three places type sits on this plate —
///    including the wordmark at the top, which is on *unscrimmed* picture
///    and is therefore the one the scrim cannot save.
void main() {
  setUpAll(loadAgentFonts);

  // ── 1. The picture, and the three reasons it is this one ───────────────
  //
  // Each of these was asserted in prose when the asset was picked. Prose goes
  // stale; a test does not.
  group('the asset is the one that was argued for', () {
    const bundled = 'assets/images/entry-plate.jpg';
    const source = '../backend/assets/places/ALL.jpg';

    test('it is byte-identical to backend ALL.jpg', () {
      final a = File(bundled).readAsBytesSync();
      final b = File(source).readAsBytesSync();
      expect(
        a,
        b,
        reason:
            'The bundled copy has drifted from the place image it was taken '
            'from. Re-copy it rather than editing it here: everything below '
            'is a claim about the ORIGINAL.',
      );
      // ignore: avoid_print
      print('entry-plate.jpg: ${a.length} bytes, identical to ALL.jpg.');
    });

    test('REASON 1: it is generated by us, so no owner licensing question', () {
      final manifest =
          jsonDecode(
                File(
                  '../backend/assets/places/manifest.json',
                ).readAsStringSync(),
              )
              as Map<String, dynamic>;
      final all = (manifest['places'] as List<dynamic>)
          .cast<Map<String, dynamic>>()
          .where((p) => p['code'] == 'ALL')
          .firstOrNull;
      expect(all, isNotNull, reason: 'ALL is not in the manifest at all');
      expect(
        all!['source'],
        'generated',
        reason:
            'If ALL ever becomes a SUPPLIED photograph it may not stay on the '
            'door: SUPPLIED_RIGHTS says this repository did not acquire or '
            'clear those and anyone reusing them needs the owner\'s '
            'permission. A bundled app asset is reuse.',
      );
      expect(all['generator'], 'gemini-3.1-flash-image');

      // And the supplied set does not claim it. `supplied.ts` is the list
      // SUPPLIED_RIGHTS attaches to; ALL being absent from it is the other
      // half of the same claim.
      final supplied = File(
        '../backend/scripts/places/supplied.ts',
      ).readAsStringSync();
      expect(
        RegExp(r"code:\s*'ALL'").hasMatch(supplied),
        isFalse,
        reason: 'ALL has joined the supplied set — see the reason above',
      );
    });

    test('REASON 2: it is the all-territories picture', () {
      final manifest =
          jsonDecode(
                File(
                  '../backend/assets/places/manifest.json',
                ).readAsStringSync(),
              )
              as Map<String, dynamic>;
      final all = (manifest['places'] as List<dynamic>)
          .cast<Map<String, dynamic>>()
          .firstWhere((p) => p['code'] == 'ALL');
      expect(
        all['label'],
        'All territories',
        reason:
            'A door before anyone knows which territory they are in may not '
            'carry a picture OF a territory. That is the whole argument for '
            'this file and not one of the other thirteen.',
      );
    });

    test('REASON 3: no readable signage, brand marks or faces', () {
      final manifest =
          jsonDecode(
                File(
                  '../backend/assets/places/manifest.json',
                ).readAsStringSync(),
              )
              as Map<String, dynamic>;
      final prompt =
          (manifest['places'] as List<dynamic>)
                  .cast<Map<String, dynamic>>()
                  .firstWhere((p) => p['code'] == 'ALL')['prompt']
              as String;

      // The generator's constraints DO apply to this one, because a model
      // made it — which is exactly what SUPPLIED_RIGHTS says is not true of
      // the twelve supplied photographs.
      for (final clause in <String>[
        'no readable text',
        'no shop signage',
        'no brand names or logos',
        'No recognisable faces',
      ]) {
        expect(
          prompt,
          contains(clause),
          reason:
              'The prompt that produced the picture on the door no longer '
              'forbids "$clause".',
        );
      }
    });
  });

  // ── 2. The reserve, and the cliff it is not allowed to have ────────────
  group('the fold arithmetic', () {
    /// EVERY NUMBER IN THIS GROUP IS RESOLVED WITH [EntryPlate.shortest].
    ///
    /// It was not, and that was its own small version of the defect this
    /// group exists for: `PlateSpec.resolve` defaults `shortest` to The
    /// Floor's 200 and the door passes 150, so the arithmetic asserted here
    /// was a different rule from the one the widget ran. It happened not to
    /// change an outcome at either of the two sizes that were checked, which
    /// is exactly why nobody noticed.
    PlateSpec at(double h, {double scale = 1.0}) => PlateSpec.resolve(
      skin: entrySkinFor(SkinMode.night),
      viewportHeight: h,
      ground: EntryPlate.groundFor(scale),
      tallest: EntryPlate.tallest,
      shortest: EntryPlate.shortest,
    );

    /// THE RESERVE, TAKEN APART ON THE REAL SCREEN.
    ///
    /// [EntryPlate.ground] is subtracted from the **viewport**, so what it has
    /// to add up to is everything in the viewport that is not the plate and
    /// still has to be seen: the shell's top inset, the gap and the first
    /// field below the plate, and the thumb zone — which is pinned outside the
    /// scroll and therefore comes off the viewport whether the plate likes it
    /// or not.
    ///
    /// Nothing below the first field is in here. The screen scrolls, and the
    /// previous two numbers (520, then 566) were wrong precisely because they
    /// reserved the whole form and then the pinned commit row on top of it.
    testWidgets('the reserve is a measurement, and these are its pieces', (
      tester,
    ) async {
      await _pumpLogin(tester, const Size(390, 844));

      final plate = tester.getRect(find.byType(TiqPlate));
      final zone = tester.getRect(find.byType(TorchThumbZone));
      final email = tester.getRect(
        find.byKey(const ValueKey<String>('login-email')),
      );

      final topInset = plate.top;
      final gap = email.top - plate.bottom;
      final measured = topInset + gap + email.height + zone.height;

      // ignore: avoid_print
      print(
        'THE RESERVE AT 390x844, 1.0x\n'
        '  shell top inset            ${topInset.toStringAsFixed(1)}\n'
        '  blockGap, plate -> field   ${gap.toStringAsFixed(1)}\n'
        '  the email field, whole     ${email.height.toStringAsFixed(1)}\n'
        '  the pinned thumb zone      ${zone.height.toStringAsFixed(1)}\n'
        '  ----------------------------------\n'
        '  measured                   ${measured.toStringAsFixed(1)}\n'
        '  EntryPlate.ground          ${EntryPlate.ground}',
      );

      expect(
        measured,
        EntryPlate.ground,
        reason:
            'The four pieces of the reserve no longer add up to '
            'EntryPlate.ground. Set it to the measured number printed above '
            '— and if the difference is the commit row, read §3 of '
            'entry_plate.dart before adding it back.',
      );
    });

    /// THE STRUCTURAL FACT THE WHOLE RESERVE RESTS ON.
    ///
    /// `EntryFrame`'s phone shape hands `primary` and `underPrimary` to
    /// `TorchShell`, which renders them in a `TorchThumbZone` that is a
    /// **sibling** of the scroll view — `Column(Expanded(body), bottom)`. The
    /// commit action is not in the scrolling column, so its height is already
    /// out of the body before the plate is asked how tall it may be.
    ///
    /// 566 counted it a second time. If this assertion ever fails, the commit
    /// row has rejoined the scroll and the reserve has to grow by its height
    /// and by whatever is between it and the first field — which is a reading
    /// of the frame, not a number to tune.
    testWidgets('the commit row is pinned outside the scroll, which is why '
        'the reserve does not contain it', (tester) async {
      await _pumpLogin(tester, const Size(390, 844));

      final scroll = tester.getRect(find.byType(Scrollable).first);
      final submit = tester.getRect(
        find.byKey(const ValueKey<String>('login-submit')),
      );
      final forgot = tester.getRect(
        find.byKey(const ValueKey<String>('login-forgot-password')),
      );

      // ignore: avoid_print
      print(
        'scroll viewport ends at ${scroll.bottom.toStringAsFixed(1)}; '
        'the commit is at ${submit.top.toStringAsFixed(1)}'
        '-${submit.bottom.toStringAsFixed(1)} and "Forgot password?" at '
        '${forgot.top.toStringAsFixed(1)}-'
        '${forgot.bottom.toStringAsFixed(1)} — both below it, in the '
        'pinned zone.',
      );

      expect(
        submit.top,
        greaterThanOrEqualTo(scroll.bottom),
        reason:
            'The commit action is inside the scroll view. The reserve in '
            'EntryPlate.ground assumes it is pinned beneath it.',
      );
      expect(forgot.top, greaterThanOrEqualTo(scroll.bottom));
      expect(
        find.descendant(
          of: find.byType(Scrollable),
          matching: find.byType(TorchThumbZone),
        ),
        findsNothing,
      );
    });

    /// WHERE 566 CAME FROM, PINNED SO IT CANNOT COME BACK.
    ///
    /// The test that "measured" 566 took the foot of the plate to the foot of
    /// the pinned bar. On a screen whose bar is on the bottom edge that is not
    /// a content height at all — it is the viewport, less the top inset, less
    /// the plate, less the bar's own bottom padding. It would have come out at
    /// whatever the phone it ran on left over, and could not have failed.
    testWidgets('the old measurement measured the bottom of the screen', (
      tester,
    ) async {
      await _pumpLogin(tester, const Size(390, 844));

      final plate = tester.getRect(find.byType(TiqPlate));
      final forgot = tester.getRect(
        find.byKey(const ValueKey<String>('login-forgot-password')),
      );
      final old = forgot.bottom - plate.bottom;
      final leftovers = 844 - plate.bottom - (844 - forgot.bottom);

      // ignore: avoid_print
      print(
        'the old reserve, re-derived: plate foot to the foot of the pinned '
        'link is ${old.toStringAsFixed(1)} — which is the same thing as '
        '844 - ${plate.bottom.toStringAsFixed(0)} - '
        '${(844 - forgot.bottom).toStringAsFixed(0)} = '
        '${leftovers.toStringAsFixed(1)}. No content in it.',
      );

      expect(old, closeTo(566, 1));
      expect(
        old,
        closeTo(leftovers, 0.01),
        reason:
            'The 566 this fix replaces was the 844dp phone arithmetic, not a '
            'measurement of anything on the screen.',
      );
    });

    /// THE FOUR SIZES, AND THE SHAPE EACH ONE RESOLVES TO.
    ///
    /// `min(clamp(0.40 × vh, 200, 250), vh − 268)`:
    ///
    /// | viewport | proportional | after the reserve | plate |
    /// |---|---|---|---|
    /// | 390×844   | 250 | 576  | **250, photographic** |
    /// | 1280×1800 | 250 | 1532 | **250, photographic** |
    /// | 395×708   | 250 | 440  | **250, photographic** |
    /// | 360×640   | 250 | 372  | **250, photographic** |
    ///
    /// 395×708 is the owner's window and the third report of the same defect.
    /// 360×640 is the row that moved: at a 566 reserve it was `74`, under
    /// every floor, and the handset got no picture.
    test('the four viewports the owner has looked at all draw the picture', () {
      for (final (name, vh) in <(String, double)>[
        ('390x844', 844),
        ('1280x1800', 1800),
        ('395x708', 708),
        ('360x640', 640),
      ]) {
        final spec = at(vh);
        // ignore: avoid_print
        print('$name -> ${spec.describe()}');
        expect(spec.form, PlateForm.photographic, reason: name);
        expect(spec.height, 250, reason: name);
      }
    });

    /// ── THE GUARD ─────────────────────────────────────────────────────────
    ///
    /// Three owner reports, three single-point fixes, three times the cliff
    /// moved instead of going away: 749, then 810-against-749, then **708,
    /// eight dp short of the 716 the last fix bought**. A test pinned to one
    /// viewport is what let that happen twice, so this one is a range.
    ///
    /// It asserts the photograph over every integer viewport height from the
    /// shortest phone anyone ships to well past the tallest browser window,
    /// at every text scale the app allows. A hole anywhere in it names the
    /// height.
    test('THE GUARD: no plausible viewport loses the picture', () {
      const lowest = 640.0; // the shortest phone in the product's range
      const highest = 1200.0;

      // The named ones, printed, so a change that moves a height shows its
      // hand in the output rather than only in a pass or a fail.
      // ignore: avoid_print
      print('  viewport      what it is                        plate');
      for (final (name, vh, what) in <(String, double, String)>[
        ('360x640', 640, 'Galaxy A04 — the shortest phone'),
        ('375x667', 667, 'iPhone SE'),
        ('395x708', 708, "THE OWNER'S BROWSER WINDOW"),
        ('1280x750', 750, 'laptop browser — report #1'),
        ('1280x700', 700, 'laptop browser, short'),
        ('390x844', 844, 'iPhone 14/15'),
        ('393x852', 852, 'iPhone 15 Pro'),
        ('412x915', 915, 'Pixel 7'),
        ('430x932', 932, 'iPhone 15 Pro Max'),
        ('1280x800', 800, 'laptop browser'),
        ('1280x900', 900, 'laptop browser, tall'),
        ('1280x1800', 1800, 'desktop browser'),
      ]) {
        final spec = at(vh);
        // ignore: avoid_print
        print(
          '  ${name.padRight(13)} ${what.padRight(33)} '
          '${spec.height.toStringAsFixed(0).padLeft(4)}dp '
          '${spec.form.name}',
        );
        expect(spec.form, PlateForm.photographic, reason: '$name — $what');
      }

      for (final scale in <double>[1.0, 1.3, 1.6, 2.0]) {
        final holes = <double>[];
        for (var vh = lowest; vh <= highest; vh++) {
          if (at(vh, scale: scale).form != PlateForm.photographic) {
            holes.add(vh);
          }
        }
        expect(
          holes,
          isEmpty,
          reason:
              'At ${scale}x the door drops the photograph at these viewport '
              'heights: ${holes.take(12).toList()}'
              '${holes.length > 12 ? ' (+${holes.length - 12} more)' : ''}. '
              'The reserve is what to re-measure, NOT EntryPlate.shortest — '
              'lowering that is the mistake this test exists to stop. See §3 '
              'of entry_plate.dart.',
        );
      }
    });

    /// WHERE THE BOUNDARY ACTUALLY SITS, FOUND RATHER THAN ASSERTED.
    ///
    /// The collapse machinery stays: under [EntryPlate.shortest] a photograph
    /// with type over it is a smear and a band of plain type is better. What
    /// this fix is about is the boundary being somewhere nobody can land on.
    /// Scanned down from the shortest phone so the number is discovered and
    /// printed, not pinned.
    test('the collapse boundary is below every device and window', () {
      const ceiling = 520.0;

      for (final scale in <double>[1.0, 2.0]) {
        var boundary = 640.0;
        while (boundary > 200 &&
            at(boundary - 1, scale: scale).form == PlateForm.photographic) {
          boundary--;
        }
        // ignore: avoid_print
        print(
          'at ${scale}x the picture survives down to a '
          '${boundary.toStringAsFixed(0)}dp viewport '
          '(reserve ${EntryPlate.groundFor(scale).toStringAsFixed(0)}, '
          'shortest ${EntryPlate.shortest}) — the band takes over below it.',
        );
        expect(
          boundary,
          lessThanOrEqualTo(ceiling),
          reason:
              'The boundary has climbed back up to $boundary at ${scale}x. '
              'Nothing in the product is that short — if this number is '
              'inside the range of real viewports again, the reserve has '
              'started counting something it should not.',
        );
      }
    });

    /// The reserve grows with the text scale, because two of its four pieces
    /// are type: the field (82 → 120) and the thumb zone (146 → 184).
    ///
    /// **This group no longer asserts a collapse at 2.0×, and that is a
    /// change.** The old one did, with the reason *"at 2.0× the form is far
    /// taller than the fold and the picture is what has to go"* — which is not
    /// a reading of this screen: the form scrolls, and what the plate was
    /// actually being measured against was a reserve of 566 times a flat,
    /// unmeasured prose share of 200. The boundary landed on 2.0× by
    /// arithmetic accident and tuning [EntryPlate.groundProse] to put it back
    /// would be the cliff engineering this file now exists to stop.
    ///
    /// It is not a free change, and the note on [EntryPlate.tallest] records
    /// what it leaves standing: at 1.3× and above the plate's headline is
    /// scaled down below the field labels under it. That is a **known,
    /// unfixed defect**, not a consequence of this group — it has been true
    /// at 1.3× and 1.6× since the screen was built, and collapsing at 2.0×
    /// would hide it rather than fix it. The lever that fixes it is a
    /// per-screen `proportion` on `PlateSpec.heightFor`; it is deferred
    /// because every measurement behind it is in Schibsted Grotesk and the prose face is
    /// under review. The table and the disproof are on `tallest`.
    for (final scale in <double>[1.0, 1.3, 1.6, 2.0]) {
      testWidgets('${scale}x: [groundFor] is not under the measured reserve', (
        tester,
      ) async {
        await _pumpLogin(tester, const Size(390, 844), textScale: scale);

        final plate = tester.getRect(find.byType(TiqPlate));
        final zone = tester.getRect(find.byType(TorchThumbZone));
        final email = tester.getRect(
          find.byKey(const ValueKey<String>('login-email')),
        );
        final measured =
            plate.top + (email.top - plate.bottom) + email.height + zone.height;
        final declared = EntryPlate.groundFor(scale);

        // ignore: avoid_print
        print(
          '${scale}x: measured reserve ${measured.toStringAsFixed(1)}, '
          'groundFor() ${declared.toStringAsFixed(1)}, '
          'plate ${plate.height.toStringAsFixed(0)}dp '
          '(field ${email.height.toStringAsFixed(0)}, '
          'zone ${zone.height.toStringAsFixed(0)})',
        );

        expect(
          declared,
          greaterThanOrEqualTo(measured),
          reason:
              'At ${scale}x the real reserve is $measured and groundFor() '
              'promises only $declared. Raise EntryPlate.groundProse until '
              'the line clears every scale.',
        );
        // The picture stays up at every scale on this phone. Pinned so the
        // change is visible rather than implied — see the note above.
        expect(_drawsPicture(tester), isTrue, reason: '${scale}x');
        await disposeEntryScreen(tester);
      });
    }

    /// THE CLAIM THE RESERVE MAKES, CHECKED WHERE IT MATTERS MOST.
    ///
    /// Not "the form fits" — it does not, and it is not meant to; the screen
    /// scrolls. The claim is that a person arriving sees the headline and the
    /// whole of the first field without touching anything. Checked at the
    /// shortest phone, at the owner's window, and at the phone the design was
    /// drawn on, against the **scroll viewport** rather than the screen —
    /// because the pinned zone is what the difference between the two is.
    for (final (name, size) in <(String, Size)>[
      ('360x640', Size(360, 640)),
      ('395x708', Size(395, 708)),
      ('390x844', Size(390, 844)),
    ]) {
      testWidgets('$name: the headline and the whole first field are above '
          'the fold, with the picture up', (tester) async {
        await _pumpLogin(tester, size);

        final plate = tester.getRect(find.byType(TiqPlate));
        final scroll = tester.getRect(find.byType(Scrollable).first);
        final email = tester.getRect(
          find.byKey(const ValueKey<String>('login-email')),
        );
        final headline = tester.getRect(find.byType(TorchDisplayHeadline));

        // ignore: avoid_print
        print(
          '$name: plate ${plate.height.toStringAsFixed(0)}dp, picture '
          '${_drawsPicture(tester) ? 'drawn' : 'DROPPED'}, headline foot '
          '${headline.bottom.toStringAsFixed(1)}, field foot '
          '${email.bottom.toStringAsFixed(1)}, fold (scroll viewport) '
          '${scroll.bottom.toStringAsFixed(1)}.',
        );

        expect(_drawsPicture(tester), isTrue, reason: name);
        expect(plate.height, 250, reason: name);
        expect(
          headline.bottom,
          lessThanOrEqualTo(scroll.bottom),
          reason: '$name: the headline is under the fold',
        );
        expect(
          email.bottom,
          lessThanOrEqualTo(scroll.bottom),
          reason:
              '$name: the first field is cut off by the fold. That is what '
              'the reserve is for — raise EntryPlate.ground, do not lower '
              'EntryPlate.shortest.',
        );
      });
    }

    testWidgets('1280x1800: the same 250dp plate, at the reading width', (
      tester,
    ) async {
      await _pumpLogin(tester, const Size(1280, 1800));

      final plate = tester.getRect(find.byType(TiqPlate));
      expect(_drawsPicture(tester), isTrue);
      // THE HEIGHT IS THE SAME AND THE WIDTH IS NOT. The plate heads a
      // column, the column is the same form at both addresses, and a plate
      // that grew with the window would be the complaint #495 exists to have
      // fixed. What changes is the crop: 480x250 instead of 358x250.
      expect(plate.height, 250);
      expect(plate.width, TiqSpace.readingWidth);
      expect(plate.center.dx, 640);
      // ignore: avoid_print
      print(
        'page shape: plate ${plate.width}x${plate.height} at the reading '
        'width, against ${390 - 2 * entrySkinFor(SkinMode.night).space.gutter}'
        'x250 on the phone.',
      );
    });
  });

  // ── 3. Amber ───────────────────────────────────────────────────────────
  group('the strip light is out, in both skins', () {
    /// THE ALLOCATION, STATED.
    ///
    /// `TorchScope`'s ladder is `primaryCommit -> plateStripLight`, so on a
    /// Day budget of one the sign-in button wins and the light loses by
    /// arithmetic. Night has two grants and could afford both; it does not get
    /// them, because an empty form carries zero amber in every skin and
    /// because a door lit differently in the two skins is two doors.
    ///
    /// So the light is claimed by nobody, in either skin, and what this test
    /// asserts is the thing that would make the census wrong: the 2px rule at
    /// `stripLightY` is `ink1` and not `flame600`.
    for (final mode in entrySkinModes) {
      testWidgets('${mode.name}: the rule at the light is ink, not flame', (
        tester,
      ) async {
        await _pumpLogin(tester, const Size(390, 844), skin: mode);
        final skin = entrySkinFor(mode);

        final rules = tester
            .widgetList<ColoredBox>(
              find.descendant(
                of: find.byType(TiqPlate),
                matching: find.byType(ColoredBox),
              ),
            )
            .map((b) => b.color)
            .toList();

        expect(
          rules,
          contains(skin.palette.ink1),
          reason: 'the strip light is missing its unlit rule entirely',
        );
        expect(
          rules,
          isNot(contains(skin.palette.flame600)),
          reason:
              'The plate lit its strip light on the door. The sign-in button '
              'is this screen\'s one amber object; see entry_plate.dart §2.',
        );
      });
    }
  });

  // ── 4. Contrast, measured over the real picture ────────────────────────
  //
  // §9g's rule: the ink over a plate is measured, never eyeballed, and the
  // worst pixel is the brightest one on a dark ground and the darkest one on
  // a light ground.
  //
  // THREE PLACES TYPE SITS, AND ONE OF THEM IS NEW. The headline and the
  // sentence are in the text-safe zone, where the bottom-up scrim is doing
  // most of the work — the same arrangement The Floor's hero is in. **The
  // wordmark is not.** It is at the top of the picture, on unscrimmed ground,
  // and the only thing holding it up is the per-skin tone: Night maps every
  // pixel into [0, #666666] and Day into [#999999, #E6E6E6]. That is the
  // claim being tested, and it is the reason this measurement had to be taken
  // rather than assumed from The Floor's numbers.
  group('the ink on the picture clears 4.5:1', () {
    const floor = 4.5;

    for (final mode in entrySkinModes) {
      testWidgets(mode.name, (tester) async {
        final skin = entrySkinFor(mode);
        final dark = mode == SkinMode.night;

        // Where the type is, in plate-relative coordinates, off the real
        // screen.
        await _pumpLogin(tester, const Size(390, 844), skin: mode);
        final origin = tester.getRect(find.byType(TiqPlate)).topLeft;
        final where = <String, Rect>{
          'headline (ink1, display)': tester
              .getRect(find.text('Sign in to get to work.'))
              .shift(-origin),
          'sentence (ink2, body)': tester
              .getRect(find.text('Use your work email and password.'))
              .shift(-origin),
          // BY TYPE, NOT `find.byType(RichText).first`. The plate's stack
          // draws the hero cluster before the top slot, so the first
          // `RichText` in the tree is the HEADLINE — measuring that and
          // calling it the wordmark quietly measured the headline's rect
          // twice, once against each ink, and reported a number for a place
          // no wordmark was.
          'wordmark TRADE/IQ (top of picture)': tester
              .getRect(find.byType(EntryBrand))
              .shift(-origin),
        };
        final ink = <String, Color>{
          'headline (ink1, display)': skin.palette.ink1,
          'sentence (ink2, body)': skin.palette.ink2,
          // The mark is TRADE in ink-1 and IQ in ink-2; ink-2 is the weaker
          // of the two, so measuring the whole mark against ink-2 is the
          // conservative reading.
          'wordmark TRADE/IQ (top of picture)': skin.palette.ink2,
        };

        // The same plate with nothing written on it, so the measurement sees
        // the ground rather than the glyphs.
        final frame = await _bareFrame(tester, skin);

        for (final entry in where.entries) {
          final worst = _worstPixel(frame, entry.value, dark: dark);
          final ratio = contrastRatio(ink[entry.key]!, worst);
          // ignore: avoid_print
          print(
            '${mode.name.padRight(5)}  ${entry.key.padRight(32)} '
            '${ratio.toStringAsFixed(2)}:1  (worst ground '
            '#${worst.toARGB32().toRadixString(16).substring(2).toUpperCase()})',
          );
          expect(
            ratio,
            greaterThanOrEqualTo(floor),
            reason: '${mode.name}: ${entry.key} is below $floor:1',
          );
        }
      });
    }

    /// WHY THE WORDMARK NEEDS A SCRIM, AS FOUR NUMBERS.
    ///
    /// The headline and the sentence sit in the text-safe zone, where the
    /// bottom-up scrim is what makes ink on a photograph a measured pairing.
    /// **The wordmark does not** — it is on the band above the strip light,
    /// and `TiqPlate.topScrim` is the parameter that was added for it. A new
    /// parameter with no failing case behind it is a parameter somebody
    /// deletes, so this is that case: the same mark, in the same place, on
    /// the same picture, with the scrim off.
    ///
    /// **Night is the one that fails, and that is the opposite of the way it
    /// looks.** Day's tone LIFTS the picture to a `#999999` floor, so the
    /// pale sky behind the mark stays pale and dark ink clears it unaided.
    /// Night's tone is a CEILING at `#666666`, and the same sky is the
    /// brightest thing in the frame — so it sits *at* the ceiling, and light
    /// `ink2` over it is 3.60:1. The half of the tone that rescues the foot
    /// of the plate is the half that hurts the top of it.
    ///
    /// This is a claim about the shipped asset, so it is measured over the
    /// shipped asset. If a picture ever arrives that clears it unaided, this
    /// fails and `topScrim` can go.
    for (final mode in entrySkinModes) {
      testWidgets('${mode.name}: and what it measures without the top scrim', (
        tester,
      ) async {
        final skin = entrySkinFor(mode);
        final dark = mode == SkinMode.night;
        await _pumpLogin(tester, const Size(390, 844), skin: mode);
        final origin = tester.getRect(find.byType(TiqPlate)).topLeft;
        final mark = tester.getRect(find.byType(EntryBrand)).shift(-origin);

        final bare = await _bareFrame(tester, skin, topScrim: false);
        final without = contrastRatio(
          skin.palette.ink2,
          _worstPixel(bare, mark, dark: dark),
        );
        // ignore: avoid_print
        print(
          '${mode.name.padRight(5)}  wordmark with NO top scrim       '
          '${without.toStringAsFixed(2)}:1',
        );
        if (mode == SkinMode.night) {
          expect(
            without,
            lessThan(floor),
            reason:
                'The Night wordmark now clears $floor:1 with no top scrim. '
                'Either the picture or the tone changed; re-derive whether '
                'TiqPlate.topScrim is still load-bearing rather than leaving '
                'it on out of habit.',
          );
        }
      });
    }
  });
}

// ── Standing it up ───────────────────────────────────────────────────────

Future<void> _pumpLogin(
  WidgetTester tester,
  Size size, {
  SkinMode skin = SkinMode.night,
  double textScale = 1.0,
}) => pumpEntryScreen(
  tester,
  const LoginScreen(),
  path: '/login',
  size: size,
  textScale: textScale,
  overrides: entryBaseOverrides(db: entryTestDb(), skin: skin),
);

/// Whether the plate actually drew the photograph, as opposed to the
/// collapsed band or the fallback drawing.
bool _drawsPicture(WidgetTester tester) => tester
    .widgetList<DecoratedBox>(
      find.descendant(
        of: find.byType(TiqPlate),
        matching: find.byType(DecoratedBox),
      ),
    )
    .any((b) => (b.decoration as BoxDecoration).image != null);

/// The sign-in plate at 390×844 with no type on it, rasterised.
///
/// The image is decoded off disk synchronously so the plate paints in the
/// frame under test, and the hero and the top slot are empty so every pixel
/// in the rects above is ground.
Future<({Uint8List bytes, int width})> _bareFrame(
  WidgetTester tester,
  TiqSkin skin, {
  bool topScrim = true,
}) async {
  final made = await tester.runAsync(() async {
    final codec = await ui.instantiateImageCodec(
      await File(EntryPlate.asset).readAsBytes(),
    );
    return (await codec.getNextFrame()).image;
  });

  tester.view
    ..physicalSize = const Size(390, 844)
    ..devicePixelRatio = 1.0;
  addTearDown(tester.view.reset);

  await tester.pumpWidget(
    MediaQuery(
      data: const MediaQueryData(size: Size(390, 844), devicePixelRatio: 1.0),
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: Theme(
          data: ThemeData(extensions: <ThemeExtension<dynamic>>[skin]),
          child: RepaintBoundary(
            key: const ValueKey<String>('entry-plate-contrast'),
            child: ColoredBox(
              color: skin.palette.ground,
              child: SizedBox(
                width: 390,
                height: 844,
                child: Column(
                  children: <Widget>[
                    Padding(
                      padding: EdgeInsets.symmetric(
                        horizontal: skin.space.gutter,
                      ),
                      child: TiqPlate(
                        claimId: EntryPlate.claimId,
                        viewportHeight: 844,
                        ground: EntryPlate.ground,
                        tallest: EntryPlate.tallest,
                        // The door's own floor, not The Floor's default —
                        // see the note at the top of the fold group.
                        shortest: EntryPlate.shortest,
                        image: _Decoded(made!),
                        topScrim: topScrim,
                        devicePixelRatio: 1.0,
                        hero: const SizedBox.shrink(),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  );
  await tester.pump();

  final boundary = tester.renderObject<RenderRepaintBoundary>(
    find.byKey(const ValueKey<String>('entry-plate-contrast')),
  );
  // `toImage` hands the layer tree to the rasteriser, which lives outside the
  // test binding's fake clock.
  final grabbed = await tester.runAsync(() async {
    final image = await boundary.toImage();
    final data = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
    final width = image.width;
    image.dispose();
    return (bytes: data!.buffer.asUint8List(), width: width);
  });
  return grabbed!;
}

/// The background pixel in [rect] that is hardest for the ink on this ground.
/// The whole bounding box of the glyphs counts, not just the strokes — the
/// conservative reading, and the one this product already uses.
Color _worstPixel(
  ({Uint8List bytes, int width}) frame,
  Rect rect, {
  required bool dark,
}) {
  Color? worst;
  var worstL = dark ? -1.0 : 2.0;
  for (var y = rect.top.ceil(); y < rect.bottom.floor(); y++) {
    for (
      var x = rect.left.ceil();
      x < math.min(rect.right.floor(), frame.width);
      x++
    ) {
      final i = (y * frame.width + x) * 4;
      final colour = Color.fromARGB(
        255,
        frame.bytes[i],
        frame.bytes[i + 1],
        frame.bytes[i + 2],
      );
      final l = relativeLuminance(colour);
      if (dark ? l > worstL : l < worstL) {
        worstL = l;
        worst = colour;
      }
    }
  }
  return worst!;
}

/// An already-decoded frame, so the plate paints in the frame under test.
class _Decoded extends ImageProvider<_Decoded> {
  _Decoded(this.image);

  final ui.Image image;

  @override
  Future<_Decoded> obtainKey(ImageConfiguration configuration) =>
      SynchronousFuture<_Decoded>(this);

  @override
  ImageStreamCompleter loadImage(_Decoded key, ImageDecoderCallback decode) =>
      OneFrameImageStreamCompleter(
        SynchronousFuture<ImageInfo>(ImageInfo(image: image)),
      );
}
