import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tradeiq_app/core/theme/torchlight/entry_skin.dart';
import 'package:tradeiq_app/core/theme/torchlight/tiq_contrast.dart';
import 'package:tradeiq_app/core/theme/torchlight/tiq_skin.dart';
import 'package:tradeiq_app/core/widgets/torchlight/display_headline.dart';
import 'package:tradeiq_app/core/widgets/torchlight/plate/plate.dart';
import 'package:tradeiq_app/features/auth/presentation/entry_brand.dart';
import 'package:tradeiq_app/features/auth/presentation/entry_plate.dart';
import 'package:tradeiq_app/features/auth/presentation/login_screen.dart';

import '../agent_harness.dart' show loadAgentFonts;
import 'entry_harness.dart';

/// THE PLATE ON THE DOOR — the pins behind `entry_plate.dart`.
///
/// `entry_look_test.dart` is the picture and `entry_amber_census_test.dart`
/// counts the light. This file answers the four questions neither can:
///
/// 1. **Is the picture the one we are allowed to ship, and is it still that
///    picture?** Three separate claims were made about `ALL.jpg` when it was
///    chosen and all three are checked here against the files that carry
///    them, not against anybody's memory.
/// 2. **Does the fold arithmetic actually produce the three shapes the design
///    claims?** A 250dp photographic plate on a 390×844 phone and on a
///    1280×1800 browser, and the collapsed band on a 360×640 handset.
/// 3. **Is the strip light out, in both skins?** The amber census counts
///    objects; this asserts the specific thing that would make that count
///    wrong, which is the plate's own light being lit.
/// 4. **Does the ink on the picture clear 4.5:1?** Measured over the real
///    asset, in both skins, at all three places type sits on this plate —
///    including the wordmark at the top, which is on *unscrimmed* picture
///    and is therefore the one the scrim cannot save.
void main() {
  setUpAll(loadAgentFonts);

  // ── 1. The picture, and the three reasons it is this one ───────────────
  //
  // Each of these was asserted in prose when the asset was picked. Prose goes
  // stale; a test does not.
  group('the asset is the one that was argued for', () {
    const bundled = 'assets/images/entry-plate.jpg';
    const source = '../backend/assets/places/ALL.jpg';

    test('it is byte-identical to backend ALL.jpg', () {
      final a = File(bundled).readAsBytesSync();
      final b = File(source).readAsBytesSync();
      expect(
        a,
        b,
        reason:
            'The bundled copy has drifted from the place image it was taken '
            'from. Re-copy it rather than editing it here: everything below '
            'is a claim about the ORIGINAL.',
      );
      // ignore: avoid_print
      print('entry-plate.jpg: ${a.length} bytes, identical to ALL.jpg.');
    });

    test('REASON 1: it is generated by us, so no owner licensing question', () {
      final manifest =
          jsonDecode(
                File('../backend/assets/places/manifest.json').readAsStringSync(),
              )
              as Map<String, dynamic>;
      final all = (manifest['places'] as List<dynamic>)
          .cast<Map<String, dynamic>>()
          .where((p) => p['code'] == 'ALL')
          .firstOrNull;
      expect(all, isNotNull, reason: 'ALL is not in the manifest at all');
      expect(
        all!['source'],
        'generated',
        reason:
            'If ALL ever becomes a SUPPLIED photograph it may not stay on the '
            'door: SUPPLIED_RIGHTS says this repository did not acquire or '
            'clear those and anyone reusing them needs the owner\'s '
            'permission. A bundled app asset is reuse.',
      );
      expect(all['generator'], 'gemini-3.1-flash-image');

      // And the supplied set does not claim it. `supplied.ts` is the list
      // SUPPLIED_RIGHTS attaches to; ALL being absent from it is the other
      // half of the same claim.
      final supplied = File(
        '../backend/scripts/places/supplied.ts',
      ).readAsStringSync();
      expect(
        RegExp(r"code:\s*'ALL'").hasMatch(supplied),
        isFalse,
        reason: 'ALL has joined the supplied set — see the reason above',
      );
    });

    test('REASON 2: it is the all-territories picture', () {
      final manifest =
          jsonDecode(
                File('../backend/assets/places/manifest.json').readAsStringSync(),
              )
              as Map<String, dynamic>;
      final all = (manifest['places'] as List<dynamic>)
          .cast<Map<String, dynamic>>()
          .firstWhere((p) => p['code'] == 'ALL');
      expect(
        all['label'],
        'All territories',
        reason:
            'A door before anyone knows which territory they are in may not '
            'carry a picture OF a territory. That is the whole argument for '
            'this file and not one of the other thirteen.',
      );
    });

    test('REASON 3: no readable signage, brand marks or faces', () {
      final manifest =
          jsonDecode(
                File('../backend/assets/places/manifest.json').readAsStringSync(),
              )
              as Map<String, dynamic>;
      final prompt =
          (manifest['places'] as List<dynamic>)
                  .cast<Map<String, dynamic>>()
                  .firstWhere((p) => p['code'] == 'ALL')['prompt']
              as String;

      // The generator's constraints DO apply to this one, because a model
      // made it — which is exactly what SUPPLIED_RIGHTS says is not true of
      // the twelve supplied photographs.
      for (final clause in <String>[
        'no readable text',
        'no shop signage',
        'no brand names or logos',
        'No recognisable faces',
      ]) {
        expect(
          prompt,
          contains(clause),
          reason:
              'The prompt that produced the picture on the door no longer '
              'forbids "$clause".',
        );
      }
    });
  });

  // ── 2. The fold, at the three sizes the owner is shown ─────────────────
  group('the fold arithmetic', () {
    /// The three sizes, and the form each one has to resolve to.
    ///
    /// The numbers are `min(clamp(0.40 × vh, 200, 250), vh − 566)`:
    ///
    /// | viewport | proportional | after the form | plate |
    /// |---|---|---|---|
    /// | 390×844   | 250 | 278  | **250, photographic** |
    /// | 1280×1800 | 250 | 1234 | **250, photographic** |
    /// | 360×640   | 250 | 74   | **under the 200 floor → collapsed** |
    ///
    /// 360×640 is the row that matters. The sign-in form on that handset
    /// already runs to the fold — "Forgot password?" was being clipped by the
    /// thumb zone in the render #494 shipped — so there is no 250dp to spend
    /// on a picture, and the plate says so itself rather than being clipped.
    test('the three viewports resolve to the three shapes', () {
      final skin = entrySkinFor(SkinMode.night);
      PlateSpec at(double h) => PlateSpec.resolve(
        skin: skin,
        viewportHeight: h,
        ground: EntryPlate.ground,
        tallest: EntryPlate.tallest,
      );

      for (final (name, spec, form, height) in <(
        String,
        PlateSpec,
        PlateForm,
        double,
      )>[
        ('390x844', at(844), PlateForm.photographic, 250),
        ('1280x1800', at(1800), PlateForm.photographic, 250),
        ('360x640', at(640), PlateForm.collapsed, 96),
      ]) {
        // ignore: avoid_print
        print('$name -> ${spec.describe()}');
        expect(spec.form, form, reason: name);
        expect(spec.height, height, reason: name);
      }
    });

    test('the reserve grows with the text scale, and the plate gives way', () {
      final skin = entrySkinFor(SkinMode.night);
      PlateForm at(double scale) => PlateSpec.resolve(
        skin: skin,
        viewportHeight: 844,
        ground: EntryPlate.groundFor(scale),
        tallest: EntryPlate.tallest,
      ).form;

      // The form under the plate is prose and prose gets bigger. A reserve
      // that did not move would keep drawing a 250dp picture over a form that
      // no longer fits under it — which is the defect, not the picture.
      expect(at(1.0), PlateForm.photographic);
      expect(at(1.3), PlateForm.photographic);
      expect(
        at(2.0),
        PlateForm.collapsed,
        reason:
            'At 2.0x the form is far taller than the fold and the picture is '
            'what has to go. `TiqTextScale.maxScale` is the cap this is '
            'measured at.',
      );
    });

    test('the reserve is not a guess: the form under it measures 566', () {
      // `EntryPlate.ground` is asserted against the rendered form in
      // "the form below the plate fits under the reserve" below. This states
      // the number so a diff names it. It was 520 when it was a guess and
      // the measurement said 566.
      expect(EntryPlate.ground, 566);
      expect(EntryPlate.tallest, 250);
    });

    testWidgets('390x844: a 250dp photographic plate, and the form below it '
        'fits under the reserve', (tester) async {
      await _pumpLogin(tester, const Size(390, 844));

      final plate = tester.getRect(find.byType(TiqPlate));
      expect(plate.height, 250);
      expect(_drawsPicture(tester), isTrue);

      // THE RESERVE, MEASURED. Everything from the foot of the plate to the
      // foot of the commit action is what `ground` is a reserve FOR, and it
      // has to actually fit in it.
      final submit = tester.getRect(
        find.byKey(const ValueKey<String>('login-submit')),
      );
      final used = submit.bottom - plate.bottom;
      // ignore: avoid_print
      print(
        '390x844: plate ${plate.height}dp, form below it '
        '${used.toStringAsFixed(1)}dp, reserve ${EntryPlate.ground}dp.',
      );
      expect(
        used,
        lessThanOrEqualTo(EntryPlate.ground),
        reason:
            'The form under the plate is taller than the reserve the plate '
            'sized itself against. Raise EntryPlate.ground to the number '
            'printed above.',
      );
    });

    testWidgets('360x640: the picture is dropped, not clipped', (tester) async {
      await _pumpLogin(tester, const Size(360, 640));

      expect(
        _drawsPicture(tester),
        isFalse,
        reason:
            'The short handset gets the collapsed band. A 250dp picture here '
            'would push the commit action off a screen whose form already '
            'runs to the fold.',
      );
      // What it keeps: the wordmark, the headline and the sentence, on the
      // ground — very nearly the masthead this screen already had.
      expect(find.byType(TorchDisplayHeadline), findsOneWidget);
      expect(find.text('Sign in to get to work.'), findsOneWidget);
      expect(find.text('Use your work email and password.'), findsOneWidget);
      expect(find.bySemanticsLabel('TradeIQ'), findsOneWidget);
    });

    testWidgets('1280x1800: the same 250dp plate, at the reading width', (
      tester,
    ) async {
      await _pumpLogin(tester, const Size(1280, 1800));

      final plate = tester.getRect(find.byType(TiqPlate));
      expect(_drawsPicture(tester), isTrue);
      // THE HEIGHT IS THE SAME AND THE WIDTH IS NOT. The plate heads a
      // column, the column is the same form at both addresses, and a plate
      // that grew with the window would be the complaint #495 exists to have
      // fixed. What changes is the crop: 480x250 instead of 358x250.
      expect(plate.height, 250);
      expect(plate.width, TiqSpace.readingWidth);
      expect(plate.center.dx, 640);
      // ignore: avoid_print
      print(
        'page shape: plate ${plate.width}x${plate.height} at the reading '
        'width, against ${390 - 2 * entrySkinFor(SkinMode.night).space.gutter}'
        'x250 on the phone.',
      );
    });
  });

  // ── 3. Amber ───────────────────────────────────────────────────────────
  group('the strip light is out, in both skins', () {
    /// THE ALLOCATION, STATED.
    ///
    /// `TorchScope`'s ladder is `primaryCommit -> plateStripLight`, so on a
    /// Day budget of one the sign-in button wins and the light loses by
    /// arithmetic. Night has two grants and could afford both; it does not get
    /// them, because an empty form carries zero amber in every skin and
    /// because a door lit differently in the two skins is two doors.
    ///
    /// So the light is claimed by nobody, in either skin, and what this test
    /// asserts is the thing that would make the census wrong: the 2px rule at
    /// `stripLightY` is `ink1` and not `flame600`.
    for (final mode in entrySkinModes) {
      testWidgets('${mode.name}: the rule at the light is ink, not flame', (
        tester,
      ) async {
        await _pumpLogin(tester, const Size(390, 844), skin: mode);
        final skin = entrySkinFor(mode);

        final rules = tester
            .widgetList<ColoredBox>(
              find.descendant(
                of: find.byType(TiqPlate),
                matching: find.byType(ColoredBox),
              ),
            )
            .map((b) => b.color)
            .toList();

        expect(
          rules,
          contains(skin.palette.ink1),
          reason: 'the strip light is missing its unlit rule entirely',
        );
        expect(
          rules,
          isNot(contains(skin.palette.flame600)),
          reason:
              'The plate lit its strip light on the door. The sign-in button '
              'is this screen\'s one amber object; see entry_plate.dart §2.',
        );
      });
    }
  });

  // ── 4. Contrast, measured over the real picture ────────────────────────
  //
  // §9g's rule: the ink over a plate is measured, never eyeballed, and the
  // worst pixel is the brightest one on a dark ground and the darkest one on
  // a light ground.
  //
  // THREE PLACES TYPE SITS, AND ONE OF THEM IS NEW. The headline and the
  // sentence are in the text-safe zone, where the bottom-up scrim is doing
  // most of the work — the same arrangement The Floor's hero is in. **The
  // wordmark is not.** It is at the top of the picture, on unscrimmed ground,
  // and the only thing holding it up is the per-skin tone: Night maps every
  // pixel into [0, #666666] and Day into [#999999, #E6E6E6]. That is the
  // claim being tested, and it is the reason this measurement had to be taken
  // rather than assumed from The Floor's numbers.
  group('the ink on the picture clears 4.5:1', () {
    const floor = 4.5;

    for (final mode in entrySkinModes) {
      testWidgets(mode.name, (tester) async {
        final skin = entrySkinFor(mode);
        final dark = mode == SkinMode.night;

        // Where the type is, in plate-relative coordinates, off the real
        // screen.
        await _pumpLogin(tester, const Size(390, 844), skin: mode);
        final origin = tester.getRect(find.byType(TiqPlate)).topLeft;
        final where = <String, Rect>{
          'headline (ink1, display)': tester
              .getRect(find.text('Sign in to get to work.'))
              .shift(-origin),
          'sentence (ink2, body)': tester
              .getRect(find.text('Use your work email and password.'))
              .shift(-origin),
          // BY TYPE, NOT `find.byType(RichText).first`. The plate's stack
          // draws the hero cluster before the top slot, so the first
          // `RichText` in the tree is the HEADLINE — measuring that and
          // calling it the wordmark quietly measured the headline's rect
          // twice, once against each ink, and reported a number for a place
          // no wordmark was.
          'wordmark TRADE/IQ (top of picture)': tester
              .getRect(find.byType(EntryBrand))
              .shift(-origin),
        };
        final ink = <String, Color>{
          'headline (ink1, display)': skin.palette.ink1,
          'sentence (ink2, body)': skin.palette.ink2,
          // The mark is TRADE in ink-1 and IQ in ink-2; ink-2 is the weaker
          // of the two, so measuring the whole mark against ink-2 is the
          // conservative reading.
          'wordmark TRADE/IQ (top of picture)': skin.palette.ink2,
        };

        // The same plate with nothing written on it, so the measurement sees
        // the ground rather than the glyphs.
        final frame = await _bareFrame(tester, skin);

        for (final entry in where.entries) {
          final worst = _worstPixel(frame, entry.value, dark: dark);
          final ratio = contrastRatio(ink[entry.key]!, worst);
          // ignore: avoid_print
          print(
            '${mode.name.padRight(5)}  ${entry.key.padRight(32)} '
            '${ratio.toStringAsFixed(2)}:1  (worst ground '
            '#${worst.toARGB32().toRadixString(16).substring(2).toUpperCase()})',
          );
          expect(
            ratio,
            greaterThanOrEqualTo(floor),
            reason: '${mode.name}: ${entry.key} is below $floor:1',
          );
        }
      });
    }

    /// WHY THE WORDMARK NEEDS A SCRIM, AS FOUR NUMBERS.
    ///
    /// The headline and the sentence sit in the text-safe zone, where the
    /// bottom-up scrim is what makes ink on a photograph a measured pairing.
    /// **The wordmark does not** — it is on the band above the strip light,
    /// and `TiqPlate.topScrim` is the parameter that was added for it. A new
    /// parameter with no failing case behind it is a parameter somebody
    /// deletes, so this is that case: the same mark, in the same place, on
    /// the same picture, with the scrim off.
    ///
    /// **Night is the one that fails, and that is the opposite of the way it
    /// looks.** Day's tone LIFTS the picture to a `#999999` floor, so the
    /// pale sky behind the mark stays pale and dark ink clears it unaided.
    /// Night's tone is a CEILING at `#666666`, and the same sky is the
    /// brightest thing in the frame — so it sits *at* the ceiling, and light
    /// `ink2` over it is 3.60:1. The half of the tone that rescues the foot
    /// of the plate is the half that hurts the top of it.
    ///
    /// This is a claim about the shipped asset, so it is measured over the
    /// shipped asset. If a picture ever arrives that clears it unaided, this
    /// fails and `topScrim` can go.
    for (final mode in entrySkinModes) {
      testWidgets('${mode.name}: and what it measures without the top scrim', (
        tester,
      ) async {
        final skin = entrySkinFor(mode);
        final dark = mode == SkinMode.night;
        await _pumpLogin(tester, const Size(390, 844), skin: mode);
        final origin = tester.getRect(find.byType(TiqPlate)).topLeft;
        final mark = tester.getRect(find.byType(EntryBrand)).shift(-origin);

        final bare = await _bareFrame(tester, skin, topScrim: false);
        final without = contrastRatio(
          skin.palette.ink2,
          _worstPixel(bare, mark, dark: dark),
        );
        // ignore: avoid_print
        print(
          '${mode.name.padRight(5)}  wordmark with NO top scrim       '
          '${without.toStringAsFixed(2)}:1',
        );
        if (mode == SkinMode.night) {
          expect(
            without,
            lessThan(floor),
            reason:
                'The Night wordmark now clears $floor:1 with no top scrim. '
                'Either the picture or the tone changed; re-derive whether '
                'TiqPlate.topScrim is still load-bearing rather than leaving '
                'it on out of habit.',
          );
        }
      });
    }
  });
}

// ── Standing it up ───────────────────────────────────────────────────────

Future<void> _pumpLogin(
  WidgetTester tester,
  Size size, {
  SkinMode skin = SkinMode.night,
}) => pumpEntryScreen(
  tester,
  const LoginScreen(),
  path: '/login',
  size: size,
  overrides: entryBaseOverrides(db: entryTestDb(), skin: skin),
);

/// Whether the plate actually drew the photograph, as opposed to the
/// collapsed band or the fallback drawing.
bool _drawsPicture(WidgetTester tester) => tester
    .widgetList<DecoratedBox>(
      find.descendant(
        of: find.byType(TiqPlate),
        matching: find.byType(DecoratedBox),
      ),
    )
    .any((b) => (b.decoration as BoxDecoration).image != null);

/// The sign-in plate at 390×844 with no type on it, rasterised.
///
/// The image is decoded off disk synchronously so the plate paints in the
/// frame under test, and the hero and the top slot are empty so every pixel
/// in the rects above is ground.
Future<({Uint8List bytes, int width})> _bareFrame(
  WidgetTester tester,
  TiqSkin skin, {
  bool topScrim = true,
}) async {
  final made = await tester.runAsync(() async {
    final codec = await ui.instantiateImageCodec(
      await File(EntryPlate.asset).readAsBytes(),
    );
    return (await codec.getNextFrame()).image;
  });

  tester.view
    ..physicalSize = const Size(390, 844)
    ..devicePixelRatio = 1.0;
  addTearDown(tester.view.reset);

  await tester.pumpWidget(
    MediaQuery(
      data: const MediaQueryData(size: Size(390, 844), devicePixelRatio: 1.0),
      child: Directionality(
        textDirection: TextDirection.ltr,
        child: Theme(
          data: ThemeData(extensions: <ThemeExtension<dynamic>>[skin]),
          child: RepaintBoundary(
            key: const ValueKey<String>('entry-plate-contrast'),
            child: ColoredBox(
              color: skin.palette.ground,
              child: SizedBox(
                width: 390,
                height: 844,
                child: Column(
                  children: <Widget>[
                    Padding(
                      padding: EdgeInsets.symmetric(
                        horizontal: skin.space.gutter,
                      ),
                      child: TiqPlate(
                        claimId: EntryPlate.claimId,
                        viewportHeight: 844,
                        ground: EntryPlate.ground,
                        tallest: EntryPlate.tallest,
                        image: _Decoded(made!),
                        topScrim: topScrim,
                        devicePixelRatio: 1.0,
                        hero: const SizedBox.shrink(),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  );
  await tester.pump();

  final boundary = tester.renderObject<RenderRepaintBoundary>(
    find.byKey(const ValueKey<String>('entry-plate-contrast')),
  );
  // `toImage` hands the layer tree to the rasteriser, which lives outside the
  // test binding's fake clock.
  final grabbed = await tester.runAsync(() async {
    final image = await boundary.toImage();
    final data = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
    final width = image.width;
    image.dispose();
    return (bytes: data!.buffer.asUint8List(), width: width);
  });
  return grabbed!;
}

/// The background pixel in [rect] that is hardest for the ink on this ground.
/// The whole bounding box of the glyphs counts, not just the strokes — the
/// conservative reading, and the one this product already uses.
Color _worstPixel(
  ({Uint8List bytes, int width}) frame,
  Rect rect, {
  required bool dark,
}) {
  Color? worst;
  var worstL = dark ? -1.0 : 2.0;
  for (var y = rect.top.ceil(); y < rect.bottom.floor(); y++) {
    for (
      var x = rect.left.ceil();
      x < math.min(rect.right.floor(), frame.width);
      x++
    ) {
      final i = (y * frame.width + x) * 4;
      final colour = Color.fromARGB(
        255,
        frame.bytes[i],
        frame.bytes[i + 1],
        frame.bytes[i + 2],
      );
      final l = relativeLuminance(colour);
      if (dark ? l > worstL : l < worstL) {
        worstL = l;
        worst = colour;
      }
    }
  }
  return worst!;
}

/// An already-decoded frame, so the plate paints in the frame under test.
class _Decoded extends ImageProvider<_Decoded> {
  _Decoded(this.image);

  final ui.Image image;

  @override
  Future<_Decoded> obtainKey(ImageConfiguration configuration) =>
      SynchronousFuture<_Decoded>(this);

  @override
  ImageStreamCompleter loadImage(_Decoded key, ImageDecoderCallback decode) =>
      OneFrameImageStreamCompleter(
        SynchronousFuture<ImageInfo>(ImageInfo(image: image)),
      );
}
